#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 20 16:03:34 2019

@author: faheem
"""
# Python program to print all 
# prime number in an interval 
fact=1
n=int(input())
for i in range(1,n+1):
    fact=fact*i
print(fact)
